version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: loyalty_postgres
    restart: always
    environment:
      POSTGRES_USER: loyalty_user
      POSTGRES_PASSWORD: Watashi12Des
      POSTGRES_DB: loyalty_program
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
